### ISSUE TITLE
 'entities_payee_id' referenced before assignment

### ISSUE THREAD

**Issue by rossdargan** [scottrobertson/fintech-to-ynab#25]
Just logging this to make sure I don't forget about it

ERROR:Fintech to YNAB:Exception on /monzo [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/src/main.py", line 47, in route_monzo
    body, code = create_transaction_from_monzo(data['data'], settings, 0)
  File "/usr/src/main.py", line 169, in create_transaction_from_monzo
    entities_payee_id=entities_payee_id,
UnboundLocalError: local variable 'entities_payee_id' referenced before assignment

**Comment by rossdargan** [comment]
This was the payload:

{"type":"transaction.created","data":{"id":"tx_00009LEJq5fRaGxbcpKrAn","created":"2017-06-07T11:34:53.15Z","description":"Top up","amount":10000,"currency":"GBP","merchant":null,"notes":"","metadata":{"is_topup":"true","stripe_card_last_four":"7906","stripe_charge_id":"ch_1ASOubGFdNCyIQQUxqTEUTqU"},"account_balance":11952,"attachments":[],"category":"mondo","is_load":true,"settled":"2017-06-08T11:34:53.15Z","local_amount":10000,"local_currency":"GBP","updated":"2017-06-08T11:34:53.548Z","account_id":"acc_00009HVrunnzw9k5ePBCkr","counterparty":{},"scheme":"gps_mastercard","dedupe_id":"1879864812214861528","originator":false,"include_in_spending":false}}
