### ISSUE TITLE
Duplicate transaction

### ISSUE THREAD

**Issue by dafyddj** [scottrobertson/fintech-to-ynab#26]
Hi,

I'm trying to get this to work with Monzo, but all my transactions are detected as duplicates. The only logging I see is:
```
2017-06-10T21:23:40.627213+00:00 app[web.1]: DEBUG:settings:A previous transaction for the payee Tesco has been found
2017-06-10T21:23:40.627384+00:00 app[web.1]: DEBUG:settings:A subcategory was not found for the previous transaction for Tesco
2017-06-10T21:23:40.627495+00:00 app[web.1]: DEBUG:settings:searching for payee Tesco
2017-06-10T21:23:40.627616+00:00 app[web.1]: DEBUG:settings:Creating transaction object
2017-06-10T21:23:40.632605+00:00 app[web.1]: DEBUG:settings:Duplicate detection
2017-06-10T21:23:40.637105+00:00 app[web.1]: DEBUG:settings:skipping due to duplicate transaction
```
I don't know if this is related to #19? Any ideas?

**Comment by rossdargan** [comment]
Are you using something like postman to post these results, or are you actually purchasing things?

**Comment by dafyddj** [comment]
These are actual purchases. I've just checked though, and it appears a top-up transaction has gone through.

**Comment by rossdargan** [comment]
The code duplication looks for transactions with the following:
Same Amount on the same date for the same payee.

Are there similar transactions for Tesco on the same day?

**Comment by dafyddj** [comment]
No, I've mostly had one transaction a day, and this message appears for all of them.

**Comment by rossdargan** [comment]
Is there anything else in the log?

**Comment by dafyddj** [comment]
Sorry, I didn't realise there was more logging than I included above. The full log for the latest transaction is [here](https://gist.github.com/dafyddj/6d5114635a4ea1200dfe2470c7227bfb).

The salient bit seems to be:
```
2017-06-12T14:28:23.089267+00:00 app[web.1]: DEBUG:pynYNAB.Client:Client.push
2017-06-12T14:28:23.226300+00:00 app[web.1]: ERROR:Fintech to YNAB:Exception on /monzo [POST]
2017-06-12T14:28:23.226304+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
2017-06-12T14:28:23.226303+00:00 app[web.1]: Traceback (most recent call last):
2017-06-12T14:28:23.226322+00:00 app[web.1]:     response = self.full_dispatch_request()
2017-06-12T14:28:23.226324+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
2017-06-12T14:28:23.226325+00:00 app[web.1]:     rv = self.handle_user_exception(e)
2017-06-12T14:28:23.226325+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
2017-06-12T14:28:23.226327+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
2017-06-12T14:28:23.226326+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2017-06-12T14:28:23.226328+00:00 app[web.1]:     rv = self.dispatch_request()
2017-06-12T14:28:23.226328+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
2017-06-12T14:28:23.226329+00:00 app[web.1]:     return self.view_functions[rule.endpoint](**req.view_args)
2017-06-12T14:28:23.226330+00:00 app[web.1]:     body, code = create_transaction_from_monzo(data['data'], settings, 0)
2017-06-12T14:28:23.226329+00:00 app[web.1]:   File "python/main.py", line 47, in route_monzo
2017-06-12T14:28:23.226331+00:00 app[web.1]:   File "python/main.py", line 188, in create_transaction_from_monzo
2017-06-12T14:28:23.226332+00:00 app[web.1]:     ynab_client.client.push(expected_delta)
2017-06-12T14:28:23.226333+00:00 app[web.1]:   File "/app/.heroku/src/pynynab/pynYNAB/Client.py", line 143, in push
2017-06-12T14:28:23.226333+00:00 app[web.1]:     raise WrongPushException(expected_delta, delta)
2017-06-12T14:28:23.226334+00:00 app[web.1]: WrongPushException
2017-06-12T14:28:23.235269+00:00 app[web.1]: INFO:werkzeug:10.10.130.233 - - [12/Jun/2017 14:28:23] "POST /monzo?secret=<redacted> HTTP/1.1" 500 -
```

**Comment by rossdargan** [comment]
It looks to me like two calls are being made at once. Can you check the webhooks in monzo and see if you have added the webhook twice please.

**Comment by rossdargan** [comment]
Never mind, checked the logs again and it doesn't appear like two calls are being made.

**Comment by rossdargan** [comment]
Ok. The issue here is for some reason we are back to getting WrongPushException when we add payees. I'll test with some dummy data and see if I can recreate. The duplicate detection is causing an issue because in our un-synchronised copy we do have the transaction added (it just never get's send to ynab).

**Comment by rossdargan** [comment]
Looks connected to #24

**Comment by ganey** [comment]
Also just had this issue today for a new payee.

Wondering if the transaction is only synced in the local copy after being successfully sent to YNAB? 
It might improve the false duplication detection, but I'm not sure on what the implications might be.

**Comment by rossdargan** [comment]
I'm thinking there is an issue with adding new payees. I'll look into it when I get a second.

**Comment by scottrobertson** [comment]
I have added full request body logging so that we can easily debug these.

**Comment by rossdargan** [comment]
@scottrobertson I've confirmed this issue. Adding a new payee causes WrongPushException.

**Comment by scottrobertson** [comment]
@rossdargan can you try it again after the latest commits i just pushed

**Comment by rossdargan** [comment]
@scottrobertson yup... confirmed fixed :)

**Comment by scottrobertson** [comment]
Awesome!
